import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Paths to cleaned data files
aqi_path = os.path.join('..', 'data', 'delhi_aqi_clean.csv')
waste_path = os.path.join('..', 'data', 'waste_bins_clean.csv')

# --- Air Quality Data Plots ---
df_aqi = pd.read_csv(aqi_path)

# Time series plot for PM2.5 and PM10
plt.figure(figsize=(12,5))
df_aqi['date'] = pd.to_datetime(df_aqi['date'])
df_aqi.set_index('date', inplace=True)
df_aqi[['pm2_5', 'pm10']].plot(ax=plt.gca())
plt.title('Delhi Air Quality: PM2.5 and PM10 Over Time')
plt.ylabel('Concentration (µg/m³)')
plt.xlabel('Date')
plt.legend(['PM2.5', 'PM10'])
plt.tight_layout()
plt.savefig('aqi_pm25_pm10_timeseries.png')
plt.close()

# Distribution of NO2, SO2, O3
pollutants = ['no2', 'so2', 'o3']
for pollutant in pollutants:
    plt.figure(figsize=(6,4))
    sns.histplot(df_aqi[pollutant], bins=30, kde=True)
    plt.title(f'{pollutant.upper()} Distribution')
    plt.tight_layout()
    plt.savefig(f'aqi_{pollutant}_distribution.png')
    plt.close()

# --- Waste Management Data Plots ---
df_waste = pd.read_csv(waste_path)

# Waste generated by city (top 10)
if 'City/District' in df_waste.columns and 'Waste Generated (Tons/Day)' in df_waste.columns:
    top_cities = df_waste.groupby('City/District')['Waste Generated (Tons/Day)'].mean().sort_values(ascending=False).head(10)
    plt.figure(figsize=(10,5))
    sns.barplot(x=top_cities.index, y=top_cities.values)
    plt.title('Top 10 Cities by Waste Generated (Tons/Day)')
    plt.ylabel('Waste Generated (Tons/Day)')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('waste_top_cities.png')
    plt.close()

# Recycling rate distribution
if 'Recycling Rate (%)' in df_waste.columns:
    plt.figure(figsize=(8,4))
    sns.histplot(df_waste['Recycling Rate (%)'], bins=20, kde=True)
    plt.title('Distribution of Recycling Rates (%)')
    plt.xlabel('Recycling Rate (%)')
    plt.tight_layout()
    plt.savefig('waste_recycling_rate.png')
    plt.close()

# Municipal Efficiency Score distribution
if 'Municipal Efficiency Score (1-10)' in df_waste.columns:
    plt.figure(figsize=(8,4))
    sns.histplot(df_waste['Municipal Efficiency Score (1-10)'], bins=10, kde=True)
    plt.title('Distribution of Municipal Efficiency Scores')
    plt.xlabel('Efficiency Score (1-10)')
    plt.tight_layout()
    plt.savefig('waste_efficiency_score.png')
    plt.close()

print('EDA plots generated. Review the graphs for insights!')
